### ISSUE TITLE
VCF with multiple chromosomes

### ISSUE THREAD

**Issue by LouisLeNezet** [seppinho/nft-vcf#4]
Hi,

I'm using nft-vcf for nf-core and it seems that we can't use it on vcf with multiple chromosomes.
Error: `The provided VCF file contains more than one chromosome. Please split your input VCF file by chromosome`
Is there a technical reason for this ?

It would be really nice to be able to use it on such vcf.

Thanks !

**Comment by seppinho** [comment]
Good point. No its not, I'll remove this check.

**Comment by seppinho** [comment]
Can you check if the latest version works for you?

**Comment by LouisLeNezet** [comment]
Hi !
It does work well 😄 
Thanks for the quick update !

**Comment by seppinho** [comment]
Awesome, let me know if other things are missing which would simplify the usage.
